// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  
  tutorialSidebar: [
    'hello',
    'intro',
    'table2',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
    // {
    //   type: 'doc',
    //   id: 'graph/population-density',
    //   label: 'Graphs',
    //   // items: ['graphs/population-density'],
    // },
    {
      type: 'category',
      // id: 'Graphs/graph1',
      label: 'Graphs',
      // href: '/linechart_for_suburbs2'
      // items: ['graphs/population-density'],
      items: [
        {
          type: 'link',
          label: 'graph1',
          // id: 'Graphs/graph1',
          href: '/linechart_for_suburbs2'
        },
        {
          type: 'doc',
          id: 'intro',
          // href: '/linechart_for_suburbs2'
        }
      ]
    }
    // {
    //   type: 'link',
    //   // id: 'Graphs/graph1',
    //   label: 'Graphs',
    //   href: '/linechart_for_suburbs2'
    //   // items: ['graphs/population-density'],
    // }
  ],
   
};

export default sidebars;
